### ISSUE TITLE
No longer working after update to latest version.

### ISSUE THREAD

**Issue by zissouz** [masaccio/ha-kingspan-watchman-sensit#20] opened 2024-01-05 09:01 UTC
Firstly, thanks for the integration its been working perfectlyFYI - Latest version of homeassistant with full restarts etc. Seems to be a dependency issue. 

Core 2024.1.0
Supervisor 2023.12.0
Operating System 11.3
Frontend 20240103.3

2024-01-05 08:09:37.496 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package kingspan-connect-sensor==3.0.2: ERROR: Cannot install kingspan-connect-sensor==3.0.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2024-01-05 08:09:40.744 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package kingspan-connect-sensor==3.0.2: ERROR: Cannot install kingspan-connect-sensor==3.0.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2024-01-05 08:09:43.991 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package kingspan-connect-sensor==3.0.2: ERROR: Cannot install kingspan-connect-sensor==3.0.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2024-01-05 08:09:43.992 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'kingspan_watchman_sensit': Requirements for kingspan_watchman_sensit not found: ['kingspan-connect-sensor==3.0.2'].

**Comment by masaccio** [comment] 2024-01-05 09:02
Dupe of #18

**Comment by zissouz** [comment] 2024-01-05 09:03
> Dupe of #18

Sorry was just trying to delete it!

**Closed by masaccio** 2024-01-05 09:02 UTC
