### ISSUE TITLE
HA OS 2024.1 breaks the integration.  Fails to load.  Log says requirements not met 

### ISSUE THREAD

**Issue by TransientWolf** [masaccio/ha-kingspan-watchman-sensit#21] opened 2024-01-05 11:03 UTC
HA OS 2024.1 breaks the integration.  Fails to load.  Log says requirements not met

**Comment by masaccio** [comment] 2024-01-05 11:11
Dupe of #18

**Closed by masaccio** 2024-01-05 11:11 UTC
